apiVersion: 0.3.0
environments:
  minikube:
    destination:
      namespace: default
      server: https://192.168.39.55:8443
    k8sVersion: v1.14.1
    path: minikube
  publish:
    destination:
      namespace: default
      server: https://192.168.39.218:8443
    k8sVersion: v1.14.1
    path: publish
kind: ksonnet.io/app
name: k8s-flink-operator
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
