/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flink.test;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.NoSuchElementException;
import org.apache.beam.runners.flink.FlinkPipelineOptions;
import org.apache.beam.runners.flink.FlinkRunner;
import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.coders.AvroCoder;
import org.apache.beam.sdk.coders.Coder;
import org.apache.beam.sdk.io.Read;
import org.apache.beam.sdk.io.UnboundedSource;
import org.apache.beam.sdk.io.UnboundedSource.CheckpointMark;
import org.apache.beam.sdk.io.UnboundedSource.UnboundedReader;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.apache.beam.sdk.transforms.Create;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.MapElements;
import org.apache.beam.sdk.transforms.ParDo;
import org.apache.beam.sdk.transforms.windowing.BoundedWindow;
import org.apache.beam.sdk.values.TypeDescriptors;
import org.apache.flink.api.java.utils.ParameterTool;
import org.joda.time.Instant;
import org.slf4j.LoggerFactory;

public class AppBatch {
    private static org.slf4j.Logger LOG = LoggerFactory.getLogger(AppBatch.class);

    public static void main(String[] args) {
        ParameterTool parameters = ParameterTool.fromArgs(args);
        String jobName = parameters.get("jobName", "Undefined-Name");
        String prop1 = parameters.get("envKey1", "-------");
        String prop2 = parameters.get("envKey2", "-------");
        LOG.info("prop1: {}", prop1);
        LOG.info("prop2: {}", prop2);
        FlinkPipelineOptions pipelineOptions =
                PipelineOptionsFactory.create().as(FlinkPipelineOptions.class);
        pipelineOptions.setJobName(jobName);
        pipelineOptions.setRunner(FlinkRunner.class);
        pipelineOptions.setParallelism(1);
        pipelineOptions.setStreaming(false);
        Pipeline p = Pipeline.create(pipelineOptions);

        p.apply(Create.of("To be, or not to be: that is the question:",
                "Whether 'tis nobler in the mind to suffer", "The slings and arrows of fortune,",
                "Or to take arms against a sea of troubles,"))

                .apply(ParDo.of(new DoFn<String, String>() {
                    private static final long serialVersionUID = 1;

                    @ProcessElement
                    public void processElement(ProcessContext c) {
                        String line = c.element();
                        for (int i = 0; i < 1000; i++) {
                            c.output(line);
                        }
                    }
                }))

                .apply(ParDo.of(new DoFn<String, String>() {
                    private static final long serialVersionUID = 1;

                    @ProcessElement
                    public void processElement(ProcessContext c) {
                        String[] words = c.element().split("\\s");
                        for (String word : words) {
                            c.output(word);
                        }
                    }
                }))

                .apply(MapElements.into(TypeDescriptors.strings()).via(word -> {
                    LOG.info("{}", word);
                    return word;
                }));

        p.run();
        LOG.info("Job should start running now...");
    }
}
