FROM flink:1.7.2

ADD start-streaming.sh /app/start-streaming.sh
ADD start-batch.sh /app/start-batch.sh
ADD check.sh /app/check.sh
ADD log4j.properties conf/log4j.properties
ADD log4j.properties conf/log4j-console.properties
ADD log4j.properties conf/log4j-cli.properties
