FROM flink:1.7.2

ADD start.sh /app/start.sh
ADD check.sh /app/check.sh
ADD log4j.properties conf/log4j.properties
ADD log4j.properties conf/log4j-console.properties
ADD log4j.properties conf/log4j-cli.properties
